name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: sudo apt install gcc-mingw-w64
    - name: Build NeKernel
      run: ./setup_amd64.sh && cd dev/Kernel && export AHCI_SUPPORT=1 && make -f amd64-ci.make all
