name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: sudo apt install mingw32
    - name: Build Repository
      run: cd dev/Kernel && make -f amd64-desktop.make all && cd ../../ && cd dev/Boot && make -f amd64-desktop.make all
